FROM python:3.10-slim-buster

WORKDIR /backend-flask
# docker run --rm -p 4567:4567 -it backend-flask
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

ENV FLASK_ENV=development

EXPOSE ${PORT}

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]